# Generated by Django 5.1.2 on 2025-04-13 13:59

import custom_designs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('design_type', models.CharField(choices=[('kurti', 'Kurti'), ('choli', 'Choli'), ('blouse', 'Blouse'), ('pant', 'Pant'), ('other', 'Other')], max_length=10)),
                ('other_design_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fabric_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to=custom_designs.models.reference_image_path)),
                ('embroidery', models.BooleanField(default=False)),
                ('measurement_mode', models.CharField(choices=[('static', 'Static (Manual Entry)'), ('dynamic', 'Dynamic (Predefined Size)')], max_length=10)),
                ('size_inputs', models.JSONField(help_text='Size measurements in JSON format')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('timeline', models.CharField(help_text='Expected delivery timeline', max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget in INR', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('done', 'Done'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_designs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
