# Generated by Django 5.1.4 on 2025-04-14 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_designs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdesign',
            name='size_inputs',
        ),
        migrations.AddField(
            model_name='customdesign',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='actual_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='completion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('ready', 'Ready for Delivery'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='custom_measurements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Advance Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='selected_color',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customdesign',
            name='standard_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='color',
            field=models.JSONField(blank=True, default=dict, help_text='Stores color in hex and name format', null=True),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='measurement_mode',
            field=models.CharField(choices=[('static', 'Standard Size'), ('dynamic', 'Custom Measurements')], default='static', max_length=10),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('ready', 'Ready for Delivery'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='timeline',
            field=models.CharField(max_length=50),
        ),
    ]
