# Generated by Django 5.1.2 on 2025-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_designs', '0002_remove_customdesign_size_inputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdesign',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
