# Generated by Django 5.1.2 on 2025-04-13 14:00

import django.db.models.deletion
import tailor_jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('job_title', models.CharField(default='Tailor Position', max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('skills', models.CharField(help_text='Comma separated skills', max_length=255)),
                ('other_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('work_mode', models.CharField(max_length=50)),
                ('sample_work', models.ImageField(blank=True, null=True, upload_to=tailor_jobs.models.sample_work_path)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailor_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
