# Generated by Django 5.1.4 on 2025-04-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='payment_status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
