# Generated by Django 5.1.4 on 2025-04-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_orders', '0002_bulkorder_advance_payment_bulkorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Advance Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
    ]
