# Generated by Django 5.1.2 on 2025-04-16 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_orders', '0003_alter_bulkorder_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BulkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_design_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('size_color', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bulk_orders.bulkorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulk_orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_designs/%Y/%m/%d/')),
                ('bulk_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bulk_orders.bulkorderitem')),
            ],
        ),
    ]
