# Generated by Django 5.1.2 on 2025-04-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_orders', '0004_product_bulkorderitem_customdesignimage'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.RemoveField(
            model_name='bulkorder',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
