# Generated by Django 5.1.4 on 2025-05-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_carrier_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
