# Generated by Django 5.1.4 on 2025-04-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_tryon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tryon_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryon_products/'),
        ),
    ]
