# Generated by Django 5.1.4 on 2025-04-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_tryon_product_tryon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_tryon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tryon_image',
        ),
    ]
